### ISSUE TITLE
Compatibility with upcoming ArchivesSpace 4.0.0 release

### ISSUE THREAD

**Issue by thimios** [dartmouth-dltg/container_management_labels#11]
Hi @jdshaw we are preparing for a code freeze in view of the upcoming major release of archivesspace. This new release will include major upgrades in various gems including rails. I tried running the master branch of container_management_labels with the master branch of archivesspace and I am getting the following error:

```
 [java] I, [2024-08-16T14:38:34.752264 #54382]  INFO -- : Completed 500 Internal Server Error in 182ms (Allocations: 0)
     [java] 
     [java] 
     [java] F, [2024-08-16T14:38:34.754443 #54382] FATAL -- :   
     [java] ActionView::Template::Error (undefined method `[]' for #<ActionView::Base:0x000000000024d8>):
     [java]      5:     </h1>
     [java]      6:   </span>
     [java]      7:   <nav class="global-header-nav">
     [java]      8:     <%= render "site/branding" %>
     [java]      9:     <ul class="list-unstyled ml-auto d-flex gap-x-2 bg-light rounded-bottom shadow-sm">
     [java]     10:       <%= render "shared/header_user" %>
     [java]     11:       <% if ArchivesSpaceHelp.enabled? %>
     [java]   
     [java] app/views/shared/_header_global.html.erb:8
     [java] app/views/layouts/application.html.erb:50
     [java] app/controllers/application_controller.rb:756:in `set_locale'
     [java] D, [2024-08-16T14:38:34.728055 #54382] DEBUG -- :   Rendering inline template
     [java] I, [2024-08-16T14:38:34.731691 #54382]  INFO -- :   Rendered inline template (Duration: 3.0ms | Allocations: 0)
     [java] D, [2024-08-16T14:38:34.736962 #54382] DEBUG -- :   Rendered site/_branding.html.erb (Duration: 2.4ms | Allocations: 0)
     [java] D, [2024-08-16T14:38:34.750133 #54382] DEBUG -- :   Rendered shared/_header_global.html.erb (Duration: 16.5ms | Allocations: 0)
     [java] I, [2024-08-16T14:38:34.751104 #54382]  INFO -- :   Rendered layout layouts/application.html.erb (Duration: 80.9ms | Allocations: 0)
     [java] I, [2024-08-16T14:38:34.752576 #54382]  INFO -- : Completed 500 Internal Server Error in 182ms (Allocations: 0)
     [java] 
     [java] 
     [java] F, [2024-08-16T14:38:34.754612 #54382] FATAL -- :   
     [java] ActionView::Template::Error (undefined method `[]' for #<ActionView::Base:0x000000000024d8>):
     [java]      5:     </h1>
     [java]      6:   </span>
     [java]      7:   <nav class="global-header-nav">
     [java]      8:     <%= render "site/branding" %>
     [java]      9:     <ul class="list-unstyled ml-auto d-flex gap-x-2 bg-light rounded-bottom shadow-sm">
     [java]     10:       <%= render "shared/header_user" %>
     [java]     11:       <% if ArchivesSpaceHelp.enabled? %>
     [java]   
     [java] app/views/shared/_header_global.html.erb:8
     [java] app/views/layouts/application.html.erb:50
     [java] app/controllers/application_controller.rb:756:in `set_locale'
     [java] D, [2024-08-16T14:38:35.057776 #54382] DEBUG -- :   Rendering layout /var/www/archivesspace/archivesspace/build/gems/jruby/3.1.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/templates/rescues/layout.erb
     [java] D, [2024-08-16T14:38:35.058362 #54382] DEBUG -- :   Rendering /var/www/archivesspace/archivesspace/build/gems/jruby/3.1.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout
     [java] D, [2024-08-16T14:38:35.074984 #54382] DEBUG -- :   Rendered /var/www/archivesspace/archivesspace/build/gems/jruby/3.1.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (Duration: 11.4ms | Allocations: 0)
     [java] I, [2024-08-16T14:38:35.813843 #54382]  INFO -- :   Rendered /var/www/archivesspace/archivesspace/build/gems/jruby/3.1.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (Duration: 755.1ms | Allocations: 0)
     [java] I, [2024-08-16T14:38:35.814176 #54382]  INFO -- :   Rendered layout /var/www/archivesspace/archivesspace/build/gems/jruby/3.1.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/templates/rescues/layout.erb (Duration: 756.0ms | Allocations: 0)
```

It seems that there will be compatibility issues with the upcoming release of archivesspace and I wanted to bring this to your attention. Let me know if I can help more.

**Comment by jdshaw** [comment]
Thanks! I'm waiting for the official code freeze before I start checking this and the other public plugins I maintain. I'm assuming there are going to be a lot of issues given all of the underlying core changes.

**Comment by Blake-** [comment]
The 4.0 release seems to work with ArchivesSpace  4.0
