### ISSUE TITLE
Doesn't Work With A Prefix?

### ISSUE THREAD

**Issue by Blake-** [dartmouth-dltg/container_management_labels#9]
Howdy, it looks like this won't run on a prefix. Seems to be find on staff.example.com but starts throwing errors on example.com/staff/

**Comment by jdshaw** [comment]
Should be fixed in all branches. I think!

**Comment by Blake-** [comment]
Didn't work for me, changing `container_management_labels/frontend/routes.rb` did the trick.

```
ArchivesSpace::Application.routes.draw do
 [AppConfig[:frontend_proxy_prefix], AppConfig[:frontend_prefix]].uniq.each do |prefix|
  scope prefix do
  match('/plugins/top_containers_labels/print_labels' => 'top_containers_labels#print_labels', :via => [:post])
  end
 end
end
```

**Comment by jdshaw** [comment]
Well... If I had actually added that to the main branch like I did with all of the other branches, *then* it would have worked....!

Thanks for spotting that! Added to main and also in the other branches.

**Comment by Blake-** [comment]
Sorry, I see that on Main but not on 3.0.1

**Comment by jdshaw** [comment]
I hadn't rolled any new releases. That's now also done, so running a release or from the code branch should work under a prefix. The new releases are v3.0.2, v2.8.1.1, v2.8.0.1, & v2.7.1.1

**Comment by Blake-** [comment]
Cool, thanks that hits where it should now. BUT, it's throwing a new error, this in on 3.0.2

```
[2022-07-26T09:23:31-04:00] ( ) org/jruby/RubyArray.java:1809:in `each'
[2022-07-26T09:23:31-04:00] ( ) uri:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:58:in `call'
[2022-07-26T09:23:31-04:00] ( ) uri:classloader:/rack/handler/servlet.rb:22:in `call'
[2022-07-26T09:23:31-04:00] ( ) F, [2022-07-26T09:23:31.196743 #76] FATAL -- :
[2022-07-26T09:23:31-04:00] ( ) F, [2022-07-26T09:23:31.197251 #76] FATAL -- : ActionView::Template::Error (no implicit conversion of String into Integer):
[2022-07-26T09:23:31-04:00] ( ) F, [2022-07-26T09:23:31.197659 #76] FATAL -- :     23:         <div class="label <%= params['label_type'] %>">
[2022-07-26T09:23:31-04:00] ( )     24:           <% params_new.each do |k,v| %>
[2022-07-26T09:23:31-04:00] ( )     25:             <% if fields.include?(k) %>
[2022-07-26T09:23:31-04:00] ( )     26:               <% if label[k].present? %>
[2022-07-26T09:23:31-04:00] ( )     27:                 <% if k.include?("barcode") %>
[2022-07-26T09:23:31-04:00] ( )     28:                   <div class="<%= k %>" data="<%= label[k] %>"></div>
[2022-07-26T09:23:31-04:00] ( )     29:                 <% else %>
[2022-07-26T09:23:31-04:00] ( ) F, [2022-07-26T09:23:31.197891 #76] FATAL -- :
[2022-07-26T09:23:31-04:00] ( ) F, [2022-07-26T09:23:31.198050 #76] FATAL -- : app/helpers/application_helper.rb:311:in `render_aspace_partial'
[2022-07-26T09:23:31-04:00] ( ) app/controllers/application_controller.rb:823:in `set_locale'
```

**Comment by jdshaw** [comment]
Hmmm. Just to confirm, you are running v3.0.2 of the plugin against v3.2.0 of AS?

Can you post your config settings related to the proxy url and the config settings for the label plugin? I'm not seeing that error locally, so it'll help to try and get my local instance setup as close as possible to yours to try and track this down!

**Comment by Blake-** [comment]
Really weird, I just tried it locally, both with a prefix and without, and it works fine. Something is different on the prod site, though it's not immediately obvious what that might be. I'll figure it out and let you know, might just be something wrong on this end now. Thanks again for looking into this!

**Comment by jdshaw** [comment]
Be very interested to know what's different! Its always 'fun' troubleshooting things like this.

Gonna leave this open until I hear back.

**Comment by Blake-** [comment]
Totally forgot about this! I think it's working, not sure what I was doing wrong 🤷 
Thanks again!
